# Edgemesh® API 🛜

The Edgemesh® APIs are organized around REST. Our API has predictable, resource/action-oriented URLs. It accepts URL search parameters and JSON-encoded request bodies for input parameters. It returns either JSON or binary-encoded responses depending on the provided Accept header. It uses standard HTTP response codes, authentication, and verbs.
Most resources require authentication to access. Requests can be authenticated via the X-API-Key header or the api-key search parameter.
This API is versioned to maintain compatibility. Follow our blog and discord for announcements of API version deprecations.
{{Base URL}https://api.edgemesh.com}


Made with ❤ by Edgemesh Corporation



